# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

irls_gaussian_identity <- function(A, b, eta, offset) {
    .Call(`_glmhdfe_irls_gaussian_identity`, A, b, eta, offset)
}

fe_gaussian_identity_foc <- function(lhs, theta) {
    .Call(`_glmhdfe_fe_gaussian_identity_foc`, lhs, theta)
}

irls_gaussian_log <- function(A, b, eta, offset) {
    .Call(`_glmhdfe_irls_gaussian_log`, A, b, eta, offset)
}

fe_gaussian_log_foc <- function(lhs, theta) {
    .Call(`_glmhdfe_fe_gaussian_log_foc`, lhs, theta)
}

irls_poisson_log <- function(A, b, eta, offset) {
    .Call(`_glmhdfe_irls_poisson_log`, A, b, eta, offset)
}

fe_poisson_log_foc <- function(lhs, theta) {
    .Call(`_glmhdfe_fe_poisson_log_foc`, lhs, theta)
}

irls_gamma_log <- function(A, b, eta, offset) {
    .Call(`_glmhdfe_irls_gamma_log`, A, b, eta, offset)
}

fe_gamma_log_foc <- function(lhs, theta) {
    .Call(`_glmhdfe_fe_gamma_log_foc`, lhs, theta)
}

irls_inverse_gaussian_log <- function(A, b, eta, offset) {
    .Call(`_glmhdfe_irls_inverse_gaussian_log`, A, b, eta, offset)
}

fe_inverse_gaussian_log_foc <- function(lhs, theta) {
    .Call(`_glmhdfe_fe_inverse_gaussian_log_foc`, lhs, theta)
}

ols <- function(X, y, full) {
    .Call(`_glmhdfe_ols`, X, y, full)
}

wls <- function(X, y, w, full) {
    .Call(`_glmhdfe_wls`, X, y, w, full)
}

wdemean <- function(var, weight) {
    .Call(`_glmhdfe_wdemean`, var, weight)
}

demean <- function(var) {
    .Call(`_glmhdfe_demean`, var)
}

wdemean_list <- function(var, weight) {
    .Call(`_glmhdfe_wdemean_list`, var, weight)
}

demean_list <- function(var) {
    .Call(`_glmhdfe_demean_list`, var)
}

gradient <- function(X, score) {
    .Call(`_glmhdfe_gradient`, X, score)
}

vcov_estimate <- function(X, grad, cluster_meat) {
    .Call(`_glmhdfe_vcov_estimate`, X, grad, cluster_meat)
}

demean_criterion <- function(X, w) {
    .Call(`_glmhdfe_demean_criterion`, X, w)
}

